### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by aa-deet-eeya** [ramanaditya/beginners#20]
The link to LearnLinux in this [README.md file](https://github.com/ramanaditya/beginners/blob/master/README.md) is broken

**Comment by ramanaditya** [comment]
Create a README.md which itself contains Refernce_books.md (It should be formatted as in other pages), we don't need seperate reference_books.md file

**Comment by ramanaditya** [comment]
Link was not broken actually there was nothing to point I have added README.md file now it will work smoothly. For now I am closing this issue feel free to open new issue if you find more errors
